### ISSUE TITLE
error after install, can't load the them

### ISSUE THREAD

**Issue by sucrecacao** [caksoylar/kakoune-mysticaltutor#1]
After installing with `plug` and running the command `:colorsheme mysticaltutor`
I got the following error:
```
.config/kak/colors/mysticaltutor.kak:47:1: 'face' unable to parse color: 'rgba:5C8EC780'
Error: 1:1: 'colorscheme' 1:2: 'evaluate-commands' 1:1: 'source' 47:1: 'face' unable to parse color: 'rgba:5C8EC780'
```

**Comment by sucrecacao** [comment]
> Another version of the colorscheme mysticaltutor-plain.kak is included for use with older versions such as the v2020.01.16 release.

I don't understand v2020.01.16 is the latest version

**Comment by sucrecacao** [comment]
Solution to get the latest:
git clone kak repo
delete kak binary located in `whereis kak`
cd to kak repo
`sudo make install`
Then the colorsheme should work

**Comment by caksoylar** [comment]
Hi, v2020.01.16 is the latest release indeed; the changes required for `mysticaltutor.kak` to work are not yet included in an official tagged release. It works with the current `master` branch. 

For what it's worth, it is pretty easy to compile kakoune if you have `gcc/g++` installed, especially if you use the `builtin-terminal-ui` branch which removes dependencies. I can help give some pointers if you consider that.

**Comment by caksoylar** [comment]
Oh, looks like I was a bit late :) Glad you got the development version working!

**Comment by sucrecacao** [comment]
Yes, I was just talking to myself :p but thanks for the quick answer and the amazing theme !  the transparent selection looks works very well, I already love it :)

**Comment by caksoylar** [comment]
No problem, glad you are enjoying it! More colorschemes should adopt the idea :)
